export const externals = [
  "react-native",
  "react",
  "react-dom",
  "react-native-date-picker",
  "@expo/vector-icons/AntDesign",
  "react-native-safe-area-context",
  "react-native-svg",
  "lottie-react-native",
  "native-base",
  "expo-haptics",
  "@loticai/lotic-analytics-service",
  "react-native-gesture-handler",
  "react-native-modalize",
  "react-native-snap-carousel",
];
